name: CMake Build

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use a GitHub runner with Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          sudo apt update
          sudo apt install -y cmake

      # Cache CMake build
      - name: Cache CMake build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .
