name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache CMake Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/cmake
            build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake \
                              libsdl2-dev \
                              libsdl2-ttf-dev \
                              pkg-config \
                              clang-format \
                              g++

      - name: Check Code Formatting
        run: clang-format -i -style=file src/*.cpp include/*.hpp

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: brick-breaker-build
          path: build/